### ISSUE TITLE
Application for a Page

### ISSUE THREAD

**Issue by acctimize** [ultimatemediaorg/goum.cf-pages#10]
### Vanity URL

acctimize

### Your (nick)name

Acctimize

### Theme

Light

### Avatar URL

https://res.cloudinary.com/analogyofpearl/image/upload/v1676034585/Acctimize/images/logo_acctimize_graphic_only.png

### Job

Web Developer

### Location

Cleveland, OH, United States

### About You

Shopify app developer - specializing in helping small and medium sized businesses create digital experiences that transform operations and drive results. Learn more at: https://acctimize.com/

### Links

Acctimize: https://acctimize.com
About: https://about.me/acctimize
Angel: https://angel.co/company/acctimize
Crunchbase: https://www.crunchbase.com/organization/acctimize
Facebook: https://www.facebook.com/acctimize
GitHub: https://github.com/acctimize
Instagram: https://www.instagram.com/acctimize
Imgur: https://imgur.com/user/Acctimize/about
Linkedin: https://www.linkedin.com/company/acctimize
Mastodon: https://mastodon.social/@acctimize
Medium: https://acctimize.medium.com/
Pinterest: https://www.pinterest.com/acctimize
Product Hunt: https://www.producthunt.com/@acctimize
Quora: https://www.quora.com/profile/Acctimize
Tumblr: https://www.tumblr.com/acctimize
Twitter: https://twitter.com/acctimize
YouTube: https://www.youtube.com/@acctimize

### Acceptable Use Policy

- [X] I agree to the [Acceptable Use Policy](https://goum.cf/pages/acceptableuse)

**Comment by C1200** [comment]
## Oh no! ❌

Your application for a goum.cf Pages profile page has been denied.
You might be able to apply for a new page after fixing the below reason(s).

Reason:
- A field in the application is malformed (Avatar URL is not an image)

**Comment by acctimize** [comment]
Oops - sorry about that. I just updated the **Avatar URL**. Would you please reconsider the application. Thank you.

**Comment by C1200** [comment]
## Yay! 🎉

Your profile page is now live at https://goum.cf/u/acctimize!
If you have any issues, questions or you just want to change some stuff feel free to open an [issue](https://github.com/ultimatemediaorg/goum.cf-pages/issues).
