### ISSUE TITLE
Application for a Page

### ISSUE THREAD

**Issue by bruhmanbruh** [ultimatemediaorg/goum.cf-pages#2]
### Vanity URL

e_e

### Your (nick)name

e_e

### Theme

Light

### Avatar URL

https://i.imgflip.com/50bgqm.jpg

### Job

Gamer

### Location

United States

### About You

hi! I usually like to play games and upload videos to youtube and i livestream on twitch and youtube!

### Links

Youtube: https://youtube.com/channel/UCR0EiRI2tAg8tt2M9i42CIg  Twitch: twitch.tv/stoopostingamongus

**Comment by C1200** [comment]
## Yay! 🎉 
Your profile page is now live at <https://goum.cf/u/e_e>!
If you have any issues, questions or you just want to change some stuff feel free to open an [issue](https://github.com/ultimatemediaorg/goum.cf-pages/issues).
