### ISSUE TITLE
Application for a Page

### ISSUE THREAD

**Issue by nick9088** [ultimatemediaorg/goum.cf-pages#3]
### Vanity URL

nick909

### Your (nick)name

nick909

### Theme

Dark

### Avatar URL

https://github.com/nick9088.png

### Job

Coder

### Location

Italy

### About You

hey all! i am nick, on this page you can find some of my links, for example my website

### Links

YouTube: https://youtube.com/channel/UC-ssfMFG9yn2mK5DV3Vxtuw
Instagram: https://instagram.com/nick909.dev
Website: https://nick909.dev
Github: https://github.com/nick9088

**Comment by C1200** [comment]
## Yay! 🎉

Your profile page is now live at https://goum.cf/u/nick909!
If you have any issues, questions or you just want to change some stuff feel free to open an [issue](https://github.com/ultimatemediaorg/goum.cf-pages/issues).
