### ISSUE TITLE
Application for a Page

### ISSUE THREAD

**Issue by goldenvape1** [ultimatemediaorg/goum.cf-pages#7]
### Vanity URL

goldenvapekw

### Your (nick)name

gvapekw

### Theme

Dark

### Avatar URL

https://github.com/C1200.png

### Job

Business

### Location

Kuwait

### About You

[Best Vape shop in Kuwait](https://www.goldenvapekw.com/) is specializing in the selling of electronic Vaping devices. There are also online vape shops.Vape shop offers a range of e-vaporizer products. They providing open Pod system,Vape mode kit,E-Liquid,Disposable Vape,Empty Pods,refill pods etc.

### Links

[airbar disposable vape](https://www.goldenvapekw.com/shop/airbar-2908)
[disposable vape pods](https://www.goldenvapekw.com/shop/category/disposable-vape-6)

**Comment by C1200** [comment]
## Oh no! ❌

Your application for a goum.cf Pages profile page has been denied.

Reason:
- Your page violates the [goum.cf Pages Acceptable Use Policy](https://goum.cf/pages/acceptableuse)
  - Impersonation (avatar)
