### ISSUE TITLE
Application for a Page

### ISSUE THREAD

**Issue by songbactructuyen2** [ultimatemediaorg/goum.cf-pages#8]
### Vanity URL

songbactructuyen2

### Your (nick)name

songbactructuyen2

### Theme

Dark

### Avatar URL

https://www.fb9.com/register?affid=110

### About You

fb9

### Acceptable Use Policy

- [X] I agree to the [Acceptable Use Policy](https://goum.cf/pages/acceptableuse)

**Comment by C1200** [comment]
## Oh no! ❌

Your application for a goum.cf Pages profile page has been denied.
You might be able to apply for a new page after fixing the below reason(s).

Reason:
- A field in the application is malformed (Avatar URL is not an image)
